### ISSUE TITLE
Prop "radius" not changing the radius on the ripple

### ISSUE THREAD

**Issue by curliq** [vigetlabs/react-ink#43]
I have a button with width 200px, the default radius (150) doesn't reach the edges, changing the radius like this doesn't change anythinng:
`<Ink radius={500}/>`

**Comment by redwallsolutions** [comment]
Same here.

**Comment by andtankian** [comment]
Inspecting source I noticed a `getMaxRadius` function inside `equations.js` that limits the _max radius_ value based on a `Math.min` function applied between width or height of parent and `radius` prop.

That's why you're passing a `radius` value and **it isn't being applied**. Your `Ink` parent component, probably a button, has width or height lower than `radius` prop value.

I'm submitting a pull request removing default value of `radius` prop and allowing `radius` be fully controlled by users `props` without a max value.

**Comment by cwmanning** [comment]
Now configurable via props (version 6.5.0) via #45.
